spring:
  application:
    name: microservicios2

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    instanceId: ${spring.application.name}:${random.value}