spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: micro1
            uri: lb://microservicio1
            predicates:
              - Path=/api/microservicio1/**
          - id: micro2
            uri: lb://microservicios2
            predicates:
              - Path=/api/microservicio2/**
          - id: tienda
            uri: http://localhost:8083
            predicates:
              - Path=/api/v1/products/**
            filters:
              - AddResponseHeader=X-Response-filter, gateway
          - id: tienda2
            uri: http://localhost:8083
            predicates:
              - Path=/api/v1/customers
              - Method=GET
            filters:
              - RedirectTo=301, https://jsonplaceholder.typicode.com/users

server:
  port: 8060

logging:
  level:
    root: info
    org.springframework.cloud.gateway: trace


