spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: micro1
            uri: lb://microservicio1
            predicates:
              - Path=/api/microservicio1/**
          - id: micro2
            uri: lb://microservicios2
            predicates:
              - Path=/api/microservicio2/**

server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    root: info
    org.springframework.cloud.gateway: trace


